name: 'qpdf-publish'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to clone'
        required: true
        type: string

jobs:
  build-release:
    runs-on: macos-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4

      # openssl@3 cmake already available in macos-latest
      - run: brew install jpeg-turbo

      - uses: actions/checkout@v4
        with:
          repository: 'qpdf/qpdf'
          ref: ${{ github.event.inputs.tag }}
          path: qpdf

      - working-directory: qpdf
        run: mkdir -p output

      - working-directory: qpdf
        run: |
          JPEG_TURBO_PREFIX=$(brew --prefix jpeg-turbo)
          OPENSSL_PREFIX=$(brew --prefix openssl@3)
          
          rm -rf "${JPEG_TURBO_PREFIX}/lib/"*.dylib
          rm -rf "${OPENSSL_PREFIX}/lib/"*.dylib
          
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES="arm64" \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_STATIC_LIBS=1 \
            -DUSE_IMPLICIT_CRYPTO=0 \
            -DREQUIRE_CRYPTO_OPENSSL=1 \
            -DCMAKE_PREFIX_PATH="${JPEG_TURBO_PREFIX};${OPENSSL_PREFIX}" \
            -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" \
            -DCMAKE_EXE_LINKER_FLAGS="-L${JPEG_TURBO_PREFIX}/lib -L${OPENSSL_PREFIX}/lib"

      - working-directory: qpdf
        run: cmake --build build --config Release --verbose

      - run: zip -r "qpdf-${{ github.event.inputs.tag }}.zip" qpdf

      - uses: ncipollo/release-action@v1
        with:
          tag: qpdf-${{ github.event.inputs.tag }}
          name: qpdf-${{ github.event.inputs.tag }}
          artifacts: 'qpdf-${{ github.event.inputs.tag }}.zip'
          allowUpdates: true