name: 'qpdf-publish'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to clone'
        required: true
        type: string

jobs:
  build-release:
    runs-on: macos-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4

      # openssl@3 cmake already available in macos-latest
      - run: brew install jpeg-turbo

      - uses: actions/checkout@v4
        with:
          repository: 'qpdf/qpdf'
          ref: ${{ github.event.inputs.tag }}
          path: qpdf

      - working-directory: qpdf
        run: mkdir -p output

      - working-directory: qpdf
        run: |
          JPEG_TURBO_PREFIX=$(brew --prefix jpeg-turbo)
          OPENSSL_PREFIX=$(brew --prefix openssl@3)
          
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DUSE_IMPLICIT_CRYPTO=0 \
            -DREQUIRE_CRYPTO_OPENSSL=1 \
            -DOpenSSL_ROOT_DIR="${OPENSSL_PREFIX}" \
            -DOpenSSL_USE_STATIC_LIBS=TRUE \
            -DJPEG_INCLUDE_DIR="${JPEG_TURBO_PREFIX}/include" \
            -DJPEG_LIBRARY="${JPEG_TURBO_PREFIX}/lib/libjpeg.a" \
            -DCMAKE_PREFIX_PATH="${JPEG_TURBO_PREFIX};${OPENSSL_PREFIX}" \
            -Wno-dev \
            -DBUILD_TESTING=OFF

      - working-directory: qpdf
        run: cmake --build build --config Release --verbose

      - run: zip -r "qpdf-${{ github.event.inputs.tag }}.zip" qpdf

      - uses: ncipollo/release-action@v1
        with:
          tag: qpdf-${{ github.event.inputs.tag }}
          name: qpdf-${{ github.event.inputs.tag }}
          artifacts: 'qpdf-${{ github.event.inputs.tag }}.zip'