name: 'resvg-publish'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to clone'
        required: true
        type: string

jobs:
  build:
    name: build-${{ matrix.artifact_arch }}
    runs-on: ${{ matrix.runner }}
    permissions: { contents: read }

    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact_arch: arm64
            runner: macos-latest
          - artifact_arch: x64
            runner: macos-15-intel

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'linebender/resvg'
          ref: ${{ github.event.inputs.tag }}
          path: resvg

      - working-directory: resvg
        run: cargo build --release

      - run: zip -r "resvg-${{ github.event.inputs.tag }}-macos-${{ matrix.artifact_arch }}.zip" resvg

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: resvg-${{ github.event.inputs.tag }}-macos-${{ matrix.artifact_arch }}
          path: resvg-${{ github.event.inputs.tag }}-macos-${{ matrix.artifact_arch }}.zip
          if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          pattern: resvg-${{ github.event.inputs.tag }}-macos-*
          path: release
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          tag: resvg-${{ github.event.inputs.tag }}
          name: resvg-${{ github.event.inputs.tag }}
          artifacts: 'release/*.zip'
          allowUpdates: true
          artifactErrorsFailBuild: true
