name: 'resvg-publish'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to clone'
        required: true
        type: string

jobs:
  build-release:
    runs-on: macos-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'linebender/resvg'
          ref: ${{ github.event.inputs.tag }}
          path: resvg

      - working-directory: resvg
        run: cargo build --release

      - run: zip -r "resvg-${{ github.event.inputs.tag }}.zip" resvg

      - uses: ncipollo/release-action@v1
        with:
          tag: resvg-${{ github.event.inputs.tag }}
          name: resvg-${{ github.event.inputs.tag }}
          artifacts: 'resvg-${{ github.event.inputs.tag }}.zip'
          allowUpdates: true